### ISSUE TITLE
IDE error for ActionUpdateThread.OLD_EDT deprecation

### ISSUE THREAD

**Issue by keeganwitt** [novotnyr/jwt-intellij-plugin#32]
I get IDE errors down in the status bar with the exception below.

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.novotnyr.idea.jwt.JwtExplorer$3' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.novotnyr.jwt-intellij-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by novotnyr** [comment]
Fixed in bdb540bec0e4ef7ebf3dcbfa7953bb3d590da5a0.
